name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag: 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git tag
      run: |
        TAG=${{ github.event.inputs.tag }}
        if [ -z "$TAG" ]; then TAG=$(git describe --abbrev=0 --tags) && TAG=$(echo $TAG | awk -F '[.]' '/./ {print $1"."$2"."$3+1}')1; fi
        if [ -z "$TAG" ]; then echo "tag is empty"; exit 1; fi 
        echo $TAG
  
